name: Test XYC_2 Module

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "modules/xyccore/**"
      - ".github/workflows/test_xyc_module.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "modules/xyccore/**"
      - ".github/workflows/test_xyc_module.yml"

jobs:
  tests:
    strategy:
      matrix:
        go-version:
          - 1.18.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Test xyccore
        run: cd ./modules/xyccore && go test -v -race ./...
